export const metadata = {
  title: "Terms & Conditions · HemeraScope",
  description: "HemeraScope subscription terms.",
};

export default function TermsPage() {
  return (
    <article className="space-y-6 text-[14px] leading-relaxed text-slate">
      <header className="space-y-1 pb-4 border-b border-[#E5E5E0]">
        <h1 className="text-3xl font-bold text-slate">HemeraScope Subscription Terms</h1>
        <p className="text-muted text-sm">Last updated: [pending — effective date] · Version 1.0</p>
      </header>

      <Section title="1. Definitions">
        <ul>
          <li><strong>Hemera</strong> — Hemera Intelligence Ltd, a company registered in England and Wales (company number [pending — Companies House]), registered office [pending — registered address].</li>
          <li><strong>Client, you, your</strong> — the organisation identified as the customer on the Order Form.</li>
          <li><strong>Order Form</strong> — the document signed by both parties identifying the subscription plan, fees, term, and authorised users.</li>
          <li><strong>Services</strong> — the HemeraScope SaaS platform and any professional services described in the Order Form, including carbon footprint reporting, supplier intelligence, and analyst work product.</li>
          <li><strong>Client Data</strong> — any data, including supplier and spend data, documents and credentials, that you upload to HemeraScope.</li>
          <li><strong>Hemera Data</strong> — reference data, scores, methodologies, code, reports, analyses, benchmarks, and aggregated anonymous data generated by Hemera.</li>
          <li><strong>Deliverables</strong> — reports, dashboards, and analyses Hemera produces for you under the Order Form.</li>
        </ul>
      </Section>

      <Section title="2. The Services">
        <p>
          <strong>2.2 What HemeraScope is.</strong> HemeraScope is an analytics product that helps
          organisations understand the carbon footprint of their spend and the ESG characteristics
          of their suppliers. Hemera combines Client Data with data from public registries
          (Companies House, HSE, SBTi, CDP) and applies recognised methodologies (DEFRA emission
          factors, Pedigree Matrix uncertainty scoring) to produce estimates, scores, and reports.
        </p>
        <p>
          <strong>2.3 What HemeraScope is not.</strong> The Services do not constitute legal,
          financial, tax, investment, or regulatory advice. Carbon figures produced by HemeraScope
          are <strong>estimates</strong> prepared using recognised but approximate methodologies
          and are <strong>not</strong> a substitute for independent verification required by
          specific regulatory regimes (e.g. SECR, CSRD, or frameworks requiring third-party
          assurance). You are responsible for any onward use, disclosure or reliance on the
          outputs.
        </p>
      </Section>

      <Section title="3. Your obligations">
        <p>You will:</p>
        <ul>
          <li>upload only Client Data you are entitled to upload and have all necessary rights to provide to Hemera;</li>
          <li>ensure Client Data is accurate, complete and up to date to the best of your knowledge;</li>
          <li>keep account credentials secure and notify us promptly of suspected unauthorised access;</li>
          <li>comply with the Acceptable Use Policy in Section 12;</li>
          <li>comply with all applicable laws, including UK GDPR.</li>
        </ul>
      </Section>

      <Section title="5. Fees and payment">
        <p>
          You will pay the fees set out on the Order Form.{" "}
          <em>[Placeholder: invoicing cadence, payment terms, accepted payment methods, late
          payment interest, VAT handling, currency — to be filled in.]</em>
        </p>
        <p>
          Fees are exclusive of VAT. We may increase fees on renewal by giving you not less than
          60 days&apos; notice before the end of the current Subscription Term.
        </p>
      </Section>

      <Section title="6. Data ownership, licences, and anonymised retention">
        <p>
          <strong>6.1 Client Data.</strong> As between you and us, you own and retain all right,
          title and interest in and to the Client Data. You grant Hemera a non-exclusive,
          worldwide, royalty-free licence to host, copy, transmit, display and process the Client
          Data solely as necessary to provide the Services and the Deliverables.
        </p>
        <p>
          <strong>6.2 Hemera Data, methodology, and Deliverables.</strong> As between you and us,
          Hemera owns and retains all right, title and interest in Hemera Data, Hemera&apos;s
          methodology, software, underlying models, reference datasets, and all intellectual
          property in Deliverables other than the Client Data embedded within them. On full
          payment, Hemera grants you a perpetual, non-exclusive, non-transferable licence to use
          the Deliverables internally for your own business purposes. You may not redistribute,
          resell, or publish the Deliverables without our prior written consent.
        </p>
        <p>
          <strong>6.3 Aggregated anonymous data.</strong> You acknowledge and agree that Hemera
          may, during and after the Subscription Term, create and retain aggregated and anonymised
          statistical information derived from Client Data and from the provision of the Services,
          provided that such information:
        </p>
        <ul>
          <li>is irreversibly anonymised so that it cannot be linked to you, to any individual supplier, or to any natural person;</li>
          <li>is aggregated across a cohort size large enough to prevent re-identification;</li>
          <li>does not include supplier names, company numbers, contact details, credentials, or any direct or indirect identifier.</li>
        </ul>
        <p>
          Hemera may use such aggregated anonymous information indefinitely for any lawful
          purpose, including benchmarking, research, methodology improvement, and publication of
          market trends. Because such information is not personal data under UK GDPR Recital 26,
          it is not subject to the return and deletion obligations in Section 14 or the DPA. See
          the{" "}
          <a href="/legal/privacy" className="text-teal hover:underline">
            Privacy Policy
          </a>{" "}
          for additional detail.
        </p>
      </Section>

      <Section title="9. Warranties and disclaimers">
        <p>
          Hemera warrants that it will perform the Services with reasonable care and skill. Except
          as expressly set out in this Agreement, all other warranties, conditions and terms —
          whether express, implied or statutory — are excluded to the fullest extent permitted by
          law. In particular, carbon, ESG and risk figures produced by HemeraScope are estimates
          based on published methodologies and Client Data, and Hemera does not warrant that they
          are suitable for, or accepted by, any specific regulatory, financial reporting, or
          assurance regime.
        </p>
      </Section>

      <Section title="10. Limitation of liability">
        <p>
          Subject to clause 10.1 (no exclusion for death, personal injury, fraud, or liabilities
          that cannot be excluded by law) and clause 10.2 (exclusions for loss of profit, revenue,
          business, goodwill, data corruption, and indirect loss), each party&apos;s total
          aggregate liability is limited to an amount equal to the fees paid or payable under the
          Order Form in the <strong>twelve (12) months</strong> immediately preceding the event
          giving rise to the claim.
        </p>
      </Section>

      <Section title="11. Term, renewal, and termination">
        <p>
          The Agreement starts on the Effective Date and continues for the Initial Term set out
          on the Order Form. It automatically renews for successive renewal terms unless either
          party gives written notice of non-renewal at least <strong>60 days</strong> before the
          end of the current term.
        </p>
      </Section>

      <Section title="14. Return and deletion of Client Data">
        <p>
          For 30 days after termination, you may export your Client Data through the HemeraScope
          user interface. After that period, Hemera will delete Client Data, except for
          aggregated anonymous data retained under Section 6.3 and except for data Hemera is
          required by law to retain.
        </p>
      </Section>

      <Section title="17. Governing law and jurisdiction">
        <p>
          This Agreement is governed by the laws of <strong>England and Wales</strong>. The courts
          of England and Wales have exclusive jurisdiction, except that Hemera may bring
          proceedings for injunctive relief or to enforce a payment obligation in any court of
          competent jurisdiction.
        </p>
      </Section>

      <aside className="mt-10 p-4 bg-paper rounded-lg border border-[#E5E5E0]">
        <p className="text-[12px] text-muted">
          <strong>Not the full document.</strong> This is an abridged version of the HemeraScope
          Subscription Terms. The full draft — including acceptable use, confidentiality, force
          majeure, publicity, and the Data Processing Agreement (Schedule 1) — is in{" "}
          <code>docs/research/2026-04-12-legal-statements.md</code>. The final version is subject
          to solicitor review before publication.
        </p>
      </aside>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-bold text-slate">{title}</h2>
      <div className="space-y-3 [&>p]:leading-relaxed [&>ul]:pl-5 [&>ul]:list-disc [&>ul>li]:mb-1">
        {children}
      </div>
    </section>
  );
}
