"""initial schema

Revision ID: 49bac4bdbab7
Revises: 
Create Date: 2026-04-06 15:03:38.796116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bac4bdbab7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('factor_type', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ef_scope_type', 'emission_factors', ['scope', 'factor_type'], unique=False)
    op.create_index('ix_ef_source_category', 'emission_factors', ['source', 'category'], unique=False)
    op.create_index(op.f('ix_emission_factors_source'), 'emission_factors', ['source'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('fiscal_year_start', sa.Date(), nullable=True),
    sa.Column('fiscal_year_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('upload_filename', sa.String(length=255), nullable=True),
    sa.Column('total_co2e', sa.Float(), nullable=True),
    sa.Column('scope1_co2e', sa.Float(), nullable=True),
    sa.Column('scope2_co2e', sa.Float(), nullable=True),
    sa.Column('scope3_co2e', sa.Float(), nullable=True),
    sa.Column('gsd_total', sa.Float(), nullable=True),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('supplier_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_supplier_id'), 'monitoring_alerts', ['supplier_id'], unique=False)
    op.create_table('supplier_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('governance_identity', sa.Float(), nullable=True),
    sa.Column('labour_ethics', sa.Float(), nullable=True),
    sa.Column('carbon_climate', sa.Float(), nullable=True),
    sa.Column('water_biodiversity', sa.Float(), nullable=True),
    sa.Column('product_supply_chain', sa.Float(), nullable=True),
    sa.Column('transparency_disclosure', sa.Float(), nullable=True),
    sa.Column('anti_corruption', sa.Float(), nullable=True),
    sa.Column('social_value', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('critical_flag', sa.Boolean(), nullable=False),
    sa.Column('staleness_penalty', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('layers_completed', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_scores_supplier_date', 'supplier_scores', ['supplier_id', 'scored_at'], unique=False)
    op.create_index(op.f('ix_supplier_scores_supplier_id'), 'supplier_scores', ['supplier_id'], unique=False)
    op.create_table('supplier_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_sources_layer', 'supplier_sources', ['supplier_id', 'layer'], unique=False)
    op.create_index(op.f('ix_supplier_sources_supplier_id'), 'supplier_sources', ['supplier_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ch_number', sa.String(length=10), nullable=True),
    sa.Column('hemera_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sic_codes', sa.JSON(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('esg_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('critical_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_ch_number'), 'suppliers', ['ch_number'], unique=True)
    op.create_index(op.f('ix_suppliers_hemera_id'), 'suppliers', ['hemera_id'], unique=True)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_date', sa.String(length=50), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_supplier', sa.String(length=255), nullable=True),
    sa.Column('raw_amount', sa.Float(), nullable=True),
    sa.Column('raw_category', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount_gbp', sa.Float(), nullable=True),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.Column('ghg_category', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('classification_method', sa.String(length=20), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_match_method', sa.String(length=20), nullable=True),
    sa.Column('ef_value', sa.Float(), nullable=True),
    sa.Column('ef_unit', sa.String(length=50), nullable=True),
    sa.Column('ef_source', sa.String(length=50), nullable=True),
    sa.Column('ef_level', sa.Integer(), nullable=True),
    sa.Column('ef_year', sa.Integer(), nullable=True),
    sa.Column('ef_region', sa.String(length=50), nullable=True),
    sa.Column('co2e_kg', sa.Float(), nullable=True),
    sa.Column('pedigree_reliability', sa.Integer(), nullable=True),
    sa.Column('pedigree_completeness', sa.Integer(), nullable=True),
    sa.Column('pedigree_temporal', sa.Integer(), nullable=True),
    sa.Column('pedigree_geographical', sa.Integer(), nullable=True),
    sa.Column('pedigree_technological', sa.Integer(), nullable=True),
    sa.Column('gsd_total', sa.Float(), nullable=True),
    sa.Column('is_sampled', sa.Boolean(), nullable=False),
    sa.Column('qc_pass', sa.Boolean(), nullable=True),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_engagement_id'), 'transactions', ['engagement_id'], unique=False)
    op.create_index('ix_transactions_engagement_scope', 'transactions', ['engagement_id', 'scope'], unique=False)
    op.create_index(op.f('ix_transactions_supplier_id'), 'transactions', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_supplier_id'), table_name='transactions')
    op.drop_index('ix_transactions_engagement_scope', table_name='transactions')
    op.drop_index(op.f('ix_transactions_engagement_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_hemera_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_ch_number'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_supplier_sources_supplier_id'), table_name='supplier_sources')
    op.drop_index('ix_supplier_sources_layer', table_name='supplier_sources')
    op.drop_table('supplier_sources')
    op.drop_index(op.f('ix_supplier_scores_supplier_id'), table_name='supplier_scores')
    op.drop_index('ix_supplier_scores_supplier_date', table_name='supplier_scores')
    op.drop_table('supplier_scores')
    op.drop_index(op.f('ix_monitoring_alerts_supplier_id'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_emission_factors_source'), table_name='emission_factors')
    op.drop_index('ix_ef_source_category', table_name='emission_factors')
    op.drop_index('ix_ef_scope_type', table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
