"""add soft delete to engagements and source metadata to emission factors

Revision ID: 53356e3310b8
Revises: 8d4f2a1e9b50
Create Date: 2026-04-22 11:04:47.203762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53356e3310b8'
down_revision: Union[str, Sequence[str], None] = '8d4f2a1e9b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission_factors', sa.Column('source_sheet', sa.String(length=100), nullable=True))
    op.add_column('emission_factors', sa.Column('source_row', sa.Integer(), nullable=True))
    op.add_column('emission_factors', sa.Column('source_hierarchy', sa.JSON(), nullable=True))
    op.add_column('engagements', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('engagements', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.alter_column('report_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('report_selections', 'selected_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('supplier_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier_findings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('report_selections', 'selected_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('report_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('engagements', 'deleted_by')
    op.drop_column('engagements', 'deleted_at')
    op.drop_column('emission_factors', 'source_hierarchy')
    op.drop_column('emission_factors', 'source_row')
    op.drop_column('emission_factors', 'source_sheet')
    # ### end Alembic commands ###
