"""hemerascope: add findings, selections, actions, ai_tasks, supplier_engagements; rename esg_score

Revision ID: 7b9fb3033ae7
Revises: c5a787667f05
Create Date: 2026-04-10 16:18:46.942487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9fb3033ae7'
down_revision: Union[str, Sequence[str], None] = 'c5a787667f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('linked_finding_ids', sa.JSON(), nullable=True),
    sa.Column('language_source', sa.String(length=20), nullable=False),
    sa.Column('ai_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_task_id'], ['ai_tasks.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_findings_active', 'supplier_findings', ['supplier_id', 'is_active'], unique=False)
    op.create_index('ix_supplier_findings_domain', 'supplier_findings', ['supplier_id', 'domain'], unique=False)
    op.create_index('ix_supplier_findings_severity', 'supplier_findings', ['supplier_id', 'severity'], unique=False)
    op.create_index(op.f('ix_supplier_findings_supplier_id'), 'supplier_findings', ['supplier_id'], unique=False)
    # ALTER TABLE operations for existing tables
    op.alter_column('suppliers', 'esg_score', new_column_name='hemera_score')
    op.add_column('suppliers', sa.Column('hemera_verified', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('supplier_scores', 'total_score', new_column_name='hemera_score')
    op.add_column('engagements', sa.Column('supplier_report_status', sa.String(length=20), nullable=True))
    op.add_column('engagements', sa.Column('supplier_report_exec_summary', sa.Text(), nullable=True))

    op.create_table('report_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('client_title', sa.String(length=255), nullable=True),
    sa.Column('client_detail', sa.Text(), nullable=True),
    sa.Column('client_language_source', sa.String(length=20), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('selected_by', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['supplier_findings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'finding_id', name='uq_report_selection_engagement_finding')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_selections')
    op.drop_index(op.f('ix_supplier_findings_supplier_id'), table_name='supplier_findings')
    op.drop_index('ix_supplier_findings_severity', table_name='supplier_findings')
    op.drop_index('ix_supplier_findings_domain', table_name='supplier_findings')
    op.drop_index('ix_supplier_findings_active', table_name='supplier_findings')
    op.drop_table('supplier_findings')
    op.drop_table('supplier_engagements')
    op.drop_table('report_actions')
    op.drop_table('ai_tasks')

    # Reverse ALTER TABLE operations
    op.drop_column('engagements', 'supplier_report_exec_summary')
    op.drop_column('engagements', 'supplier_report_status')
    op.alter_column('supplier_scores', 'hemera_score', new_column_name='total_score')
    op.drop_column('suppliers', 'hemera_verified')
    op.alter_column('suppliers', 'hemera_score', new_column_name='esg_score')
    # ### end Alembic commands ###
