"""add admin_notes display_name uploaded_by_email to engagements

Revision ID: c5a787667f05
Revises: f7b6b1395f47
Create Date: 2026-04-08 00:59:18.153480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a787667f05'
down_revision: Union[str, Sequence[str], None] = 'f7b6b1395f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('uploaded_by_email', sa.String(length=255), nullable=True))
    op.add_column('engagements', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('engagements', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('clerk_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'clerk_id')
    op.drop_column('engagements', 'admin_notes')
    op.drop_column('engagements', 'display_name')
    op.drop_column('engagements', 'uploaded_by_email')
    # ### end Alembic commands ###
