"""add foreign keys

Revision ID: f7b6b1395f47
Revises: 49bac4bdbab7
Create Date: 2026-04-06 15:30:43.372129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b6b1395f47'
down_revision: Union[str, Sequence[str], None] = '49bac4bdbab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'monitoring_alerts', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'supplier_scores', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'supplier_sources', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'engagements', ['engagement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'supplier_sources', type_='foreignkey')
    op.drop_constraint(None, 'supplier_scores', type_='foreignkey')
    op.drop_constraint(None, 'monitoring_alerts', type_='foreignkey')
    # ### end Alembic commands ###
